import type {
  AuditLogEntry,
  Candidate,
  DepartmentHeadcount,
  Employee,
  OnboardingHire,
  PayrollDistribution,
  PolicyDocument,
  PtoTrendPoint,
  RoleProfile,
  SecurityRole,
} from "./types";

// ---------------------------------------------------------------------------
// Mock data store. Replace with FastAPI / Azure SQL REST calls later — every
// component reads from the typed selectors in `lib/store.ts`, never from here
// directly, so the swap is isolated.
// ---------------------------------------------------------------------------

export const ROLE_PROFILES: Record<SecurityRole, RoleProfile> = {
  admin: {
    id: "admin",
    label: "HR Administrator",
    rbacTier: "Level 4 (Full Access)",
    clearance: "Encryption Active",
    canViewPayroll: true,
    canViewPII: true,
  },
  recruiter: {
    id: "recruiter",
    label: "Standard Recruiter",
    rbacTier: "Level 2 (Restricted)",
    clearance: "Data Masking Enforced",
    canViewPayroll: false,
    canViewPII: false,
  },
};

export const CURRENT_ADMIN = {
  name: "Jordan Rivera",
  title: "HR Operations Director",
  team: "Team ClosedAI",
};

export const EMPLOYEES: Employee[] = [
  {
    id: "1042",
    name: "Sarah Chen",
    title: "Senior Software Engineer",
    department: "Engineering",
    managerName: "Marcus Lee",
    email: "sarah.chen@closedai.com",
    phone: "+1 (206) 555-0142",
    location: "Seattle, WA",
    initials: "SC",
    employmentType: "Full-time",
    startDate: "2021-03-15",
    status: "Active",
    ptoRemainingHours: 72,
    ptoUsedHours: 88,
    ptoAccruedHours: 160,
    upcomingLeave: { start: "2026-08-17", end: "2026-08-21", type: "Vacation" },
    nextPayday: "2026-08-01",
    annualSalary: 168000,
    payRate: "$80.77 / hr",
  },
  {
    id: "1043",
    name: "Marcus Lee",
    title: "Engineering Manager",
    department: "Engineering",
    managerName: "Sofia Alvarez",
    email: "marcus.lee@closedai.com",
    phone: "+1 (512) 555-0199",
    location: "Austin, TX",
    initials: "ML",
    employmentType: "Full-time",
    startDate: "2019-06-01",
    status: "Active",
    ptoRemainingHours: 104,
    ptoUsedHours: 56,
    ptoAccruedHours: 160,
    upcomingLeave: null,
    nextPayday: "2026-08-01",
    annualSalary: 205000,
    payRate: "$98.55 / hr",
  },
  {
    id: "1044",
    name: "Priya Nair",
    title: "Product Designer",
    department: "Design",
    managerName: "David Chen",
    email: "priya.nair@closedai.com",
    phone: "+1 (206) 555-0177",
    location: "Seattle, WA",
    initials: "PN",
    employmentType: "Full-time",
    startDate: "2022-01-10",
    status: "On Leave",
    ptoRemainingHours: 40,
    ptoUsedHours: 120,
    ptoAccruedHours: 160,
    upcomingLeave: { start: "2026-07-28", end: "2026-08-08", type: "Parental" },
    nextPayday: "2026-08-01",
    annualSalary: 142000,
    payRate: "$68.27 / hr",
  },
  {
    id: "1045",
    name: "David Chen",
    title: "Director of Product",
    department: "Product",
    managerName: "Sofia Alvarez",
    email: "david.chen@closedai.com",
    phone: "+1 (917) 555-0110",
    location: "New York, NY",
    initials: "DC",
    employmentType: "Full-time",
    startDate: "2018-09-20",
    status: "Active",
    ptoRemainingHours: 128,
    ptoUsedHours: 32,
    ptoAccruedHours: 160,
    upcomingLeave: null,
    nextPayday: "2026-08-01",
    annualSalary: 232000,
    payRate: "$111.54 / hr",
  },
  {
    id: "1046",
    name: "Fatima Khan",
    title: "People Operations Lead",
    department: "Human Resources",
    managerName: "Jordan Rivera",
    email: "fatima.khan@closedai.com",
    phone: "+1 (206) 555-0155",
    location: "Seattle, WA",
    initials: "FK",
    employmentType: "Full-time",
    startDate: "2020-11-02",
    status: "Active",
    ptoRemainingHours: 96,
    ptoUsedHours: 64,
    ptoAccruedHours: 160,
    upcomingLeave: null,
    nextPayday: "2026-08-01",
    annualSalary: 138000,
    payRate: "$66.35 / hr",
  },
  {
    id: "1047",
    name: "Tom Becker",
    title: "Payroll Specialist",
    department: "Finance",
    managerName: "Nina Petrova",
    email: "tom.becker@closedai.com",
    phone: "+1 (312) 555-0121",
    location: "Chicago, IL",
    initials: "TB",
    employmentType: "Full-time",
    startDate: "2023-02-13",
    status: "Active",
    ptoRemainingHours: 60,
    ptoUsedHours: 20,
    ptoAccruedHours: 120,
    upcomingLeave: { start: "2026-09-14", end: "2026-09-16", type: "Vacation" },
    nextPayday: "2026-08-01",
    annualSalary: 96000,
    payRate: "$46.15 / hr",
  },
  {
    id: "1048",
    name: "Grace Okafor",
    title: "Senior Recruiter",
    department: "Human Resources",
    managerName: "Fatima Khan",
    email: "grace.okafor@closedai.com",
    phone: "+1 (646) 555-0188",
    location: "Remote",
    initials: "GO",
    employmentType: "Full-time",
    startDate: "2022-08-08",
    status: "Active",
    ptoRemainingHours: 80,
    ptoUsedHours: 80,
    ptoAccruedHours: 160,
    upcomingLeave: null,
    nextPayday: "2026-08-01",
    annualSalary: 118000,
    payRate: "$56.73 / hr",
  },
  {
    id: "1049",
    name: "Liam O'Brien",
    title: "Backend Engineer",
    department: "Engineering",
    managerName: "Marcus Lee",
    email: "liam.obrien@closedai.com",
    phone: "+1 (512) 555-0166",
    location: "Austin, TX",
    initials: "LO",
    employmentType: "Full-time",
    startDate: "2024-04-22",
    status: "Onboarding",
    ptoRemainingHours: 40,
    ptoUsedHours: 0,
    ptoAccruedHours: 40,
    upcomingLeave: null,
    nextPayday: "2026-08-01",
    annualSalary: 152000,
    payRate: "$73.08 / hr",
  },
  {
    id: "1050",
    name: "Nina Petrova",
    title: "VP of Finance",
    department: "Finance",
    managerName: "Jordan Rivera",
    email: "nina.petrova@closedai.com",
    phone: "+1 (415) 555-0133",
    location: "Remote",
    initials: "NP",
    employmentType: "Full-time",
    startDate: "2017-05-30",
    status: "Active",
    ptoRemainingHours: 152,
    ptoUsedHours: 8,
    ptoAccruedHours: 160,
    upcomingLeave: null,
    nextPayday: "2026-08-01",
    annualSalary: 268000,
    payRate: "$128.85 / hr",
  },
  {
    id: "1051",
    name: "Sofia Alvarez",
    title: "Chief People Officer",
    department: "Executive",
    managerName: "—",
    email: "sofia.alvarez@closedai.com",
    phone: "+1 (206) 555-0100",
    location: "Seattle, WA",
    initials: "SA",
    employmentType: "Full-time",
    startDate: "2016-01-04",
    status: "Active",
    ptoRemainingHours: 120,
    ptoUsedHours: 40,
    ptoAccruedHours: 160,
    upcomingLeave: null,
    nextPayday: "2026-08-01",
    annualSalary: 315000,
    payRate: "$151.44 / hr",
  },
];

export const DEPARTMENT_HEADCOUNT: DepartmentHeadcount[] = [
  { department: "Engineering", headcount: 84, openReqs: 6 },
  { department: "Product", headcount: 32, openReqs: 2 },
  { department: "Design", headcount: 21, openReqs: 1 },
  { department: "Human Resources", headcount: 14, openReqs: 1 },
  { department: "Finance", headcount: 18, openReqs: 0 },
  { department: "Sales", headcount: 47, openReqs: 4 },
];

export const PTO_TREND: PtoTrendPoint[] = [
  { month: "Feb", requested: 210, approved: 198 },
  { month: "Mar", requested: 245, approved: 232 },
  { month: "Apr", requested: 320, approved: 305 },
  { month: "May", requested: 410, approved: 388 },
  { month: "Jun", requested: 512, approved: 476 },
  { month: "Jul", requested: 638, approved: 590 },
  { month: "Aug", requested: 720, approved: 664 },
];

export const PAYROLL_DISTRIBUTION: PayrollDistribution[] = [
  { band: "$60–100k", employees: 42, totalCost: 3360000 },
  { band: "$100–150k", employees: 96, totalCost: 11520000 },
  { band: "$150–200k", employees: 54, totalCost: 9450000 },
  { band: "$200k+", employees: 24, totalCost: 6000000 },
];

export const POLICY_DOCS: PolicyDocument[] = [
  {
    id: "pol-pto",
    title: "Paid Time Off & Consecutive Leave",
    filename: "PTO_2026.pdf",
    topic: "pto",
    section: "§4.2",
    snippet:
      "Employees may take up to 10 consecutive business days of PTO without additional approval. Requests exceeding 10 consecutive days require written manager approval and 3 weeks advance notice.",
    updated: "2026-01-12",
  },
  {
    id: "pol-sick",
    title: "Sick Leave Policy",
    filename: "Sick_Leave_2026.pdf",
    topic: "sick",
    section: "§4.5",
    snippet:
      "Employees accrue 6 sick days annually. A physician's note is required for any absence exceeding 3 consecutive days.",
    updated: "2026-01-12",
  },
  {
    id: "pol-benefits",
    title: "Benefits Enrollment Handbook",
    filename: "Benefits_2026.pdf",
    topic: "benefits",
    section: "§7.1",
    snippet:
      "Open enrollment runs each November. Qualifying life events allow mid-year changes within 30 days of the event.",
    updated: "2026-01-12",
  },
  {
    id: "pol-payroll",
    title: "Payroll & Compensation Schedule",
    filename: "Payroll_Schedule_2026.pdf",
    topic: "payroll",
    section: "§3.4",
    snippet:
      "Compensation is issued semi-monthly on the 1st and 16th. Direct deposit changes take one full cycle to take effect.",
    updated: "2026-01-12",
  },
  {
    id: "pol-conduct",
    title: "Code of Conduct & Compliance",
    filename: "Code_of_Conduct_2026.pdf",
    topic: "compliance",
    section: "§1.0",
    snippet:
      "All personnel must complete annual compliance certification. Data handling must follow SOC 2 and regional privacy regulations.",
    updated: "2026-02-01",
  },
];

export const CANDIDATES: Candidate[] = [
  {
    id: "cand-01",
    name: "Elena Volkov",
    role: "Senior Backend Developer",
    matchScore: 94,
    yearsExperience: 9,
    education: "M.S. Computer Science, ETH Zürich",
    location: "Remote (EU)",
    topSkills: ["Python", "Go", "Distributed Systems", "PostgreSQL", "Azure"],
    missingSkills: ["Kafka"],
    compliance: "Cleared",
    summary:
      "Led payments platform scaling to 40k RPS. Strong distributed-systems background and cloud-native experience.",
    resumeFile: "elena_volkov_resume.pdf",
  },
  {
    id: "cand-02",
    name: "Raj Patel",
    role: "Senior Backend Developer",
    matchScore: 88,
    yearsExperience: 7,
    education: "B.S. Software Engineering, UT Austin",
    location: "Austin, TX",
    topSkills: ["Java", "Spring", "Kafka", "AWS", "Microservices"],
    missingSkills: ["Go", "Azure"],
    compliance: "Cleared",
    summary:
      "Built event-driven microservices for a fintech at scale. Deep JVM and streaming experience.",
    resumeFile: "raj_patel_resume.pdf",
  },
  {
    id: "cand-03",
    name: "Mia Rodriguez",
    role: "Senior Backend Developer",
    matchScore: 81,
    yearsExperience: 6,
    education: "B.S. Computer Science, Georgia Tech",
    location: "Atlanta, GA",
    topSkills: ["Node.js", "TypeScript", "GraphQL", "PostgreSQL"],
    missingSkills: ["Go", "Distributed Systems"],
    compliance: "Pending",
    summary:
      "Full-stack leaning backend. Strong API design; background check pending completion.",
    resumeFile: "mia_rodriguez_resume.pdf",
  },
  {
    id: "cand-04",
    name: "Ahmed Hassan",
    role: "Senior Backend Developer",
    matchScore: 63,
    yearsExperience: 4,
    education: "B.S. Information Systems, NYU",
    location: "New York, NY",
    topSkills: ["Python", "Django", "MySQL"],
    missingSkills: ["Go", "Azure", "Distributed Systems", "Seniority"],
    compliance: "Flagged",
    summary:
      "Solid mid-level engineer; experience below the senior bar for this req. Employment-gap flag for review.",
    resumeFile: "ahmed_hassan_resume.pdf",
  },
];

export const ONBOARDING_HIRES: OnboardingHire[] = [
  {
    id: "1049",
    name: "Liam O'Brien",
    role: "Backend Engineer",
    startDate: "2026-08-04",
    initials: "LO",
    tasks: [
      { id: "t1", label: "Signed offer letter", owner: "People Ops", category: "Paperwork", status: "complete", due: "2026-07-20" },
      { id: "t2", label: "I-9 & tax forms submitted", owner: "Employee", category: "Paperwork", status: "complete", due: "2026-07-28" },
      { id: "t3", label: "Provision laptop & accounts", owner: "IT", category: "IT", status: "in-progress", due: "2026-08-01" },
      { id: "t4", label: "Security & compliance training", owner: "Employee", category: "Compliance", status: "pending", due: "2026-08-08" },
      { id: "t5", label: "Assign onboarding buddy", owner: "Manager", category: "Culture", status: "pending", due: "2026-08-04" },
      { id: "t6", label: "Benefits enrollment", owner: "Employee", category: "Paperwork", status: "pending", due: "2026-08-18" },
    ],
  },
];

export const AUDIT_LOGS: AuditLogEntry[] = [
  { id: "a1", timestamp: "2026-07-30 14:02:11", actor: "Jordan Rivera", rbacTier: "Level 4", action: "Queried PTO balance", system: "Azure SQL", resource: "employee:1042", status: "success" },
  { id: "a2", timestamp: "2026-07-30 14:02:12", actor: "Jordan Rivera", rbacTier: "Level 4", action: "RAG retrieval", system: "Azure AI Search", resource: "PTO_2026.pdf", status: "success" },
  { id: "a3", timestamp: "2026-07-30 13:47:55", actor: "Grace Okafor", rbacTier: "Level 2", action: "Attempted payroll export", system: "Azure SQL", resource: "payroll:all", status: "blocked" },
  { id: "a4", timestamp: "2026-07-30 13:31:09", actor: "System Agent", rbacTier: "Level 4", action: "Resume rank & compliance scan", system: "MCP Tool", resource: "req:senior-backend", status: "success" },
  { id: "a5", timestamp: "2026-07-30 12:58:44", actor: "System Agent", rbacTier: "Level 4", action: "Topic guardrail triggered", system: "Guardrail Engine", resource: "chat:off-topic", status: "warning" },
  { id: "a6", timestamp: "2026-07-30 11:20:03", actor: "Fatima Khan", rbacTier: "Level 4", action: "Sent approval email", system: "Microsoft Graph API", resource: "employee:1042", status: "success" },
  { id: "a7", timestamp: "2026-07-30 09:14:37", actor: "Jordan Rivera", rbacTier: "Level 4", action: "Updated onboarding checklist", system: "Azure SQL", resource: "hire:1049", status: "success" },
];
